### ISSUE TITLE
[PROPOSAL] Public poll - Standard pip installation

### ISSUE THREAD

**Issue by leopoldhub** [TamtamHero/fw-fanctrl#73]
Hi,

Currently, the installation process manually moves the Python script to `/usr/bin/fw-fanctrl` (or other configured path).
This is a manual non-standard process that is only valid for single-file scripts.

I think that we should use the "[standard](https://docs.python.org/3.10/distutils/setupscript.html)" way of doing this with a `setup.py` file descriptor and install it with `pip install` instead.

> This method uses the [setuptools](https://setuptools.pypa.io/en/latest/userguide/quickstart.html).
> Several formats for the setup file are available `pyproject.toml`, `setup.cfg` and `setup.py`.
> The exact format is yet to be decided.

This would allow us to split the already large (633 lines) script file into modules, as well as allow for versioning and possible future dependencies and developement dependencies (e.g. a file formatter or tests to ensure uniformity and stability).

What do you think about this this?

**_This is a public poll, feel free to give your opinion and discuss this proposal even if you are not an active developer on this project 😉_**

**Comment by Svenum** [comment]
The `packaging/nix` already uses this: https://github.com/TamtamHero/fw-fanctrl/blob/c79c43e566d46b1767fa5af95d36f5a7049b3818/nix/packages/fw-fanctrl.nix#L24-L40

**Comment by leopoldhub** [comment]
Hi @Svenum,

Thanks for your feedback.

Nice to see that this is already being used in some way!

What do you think about other formats, and why did you choose the `setup.py` one?

**Comment by Svenum** [comment]
I used it as it is the recommended way from nixos to package a python package. Thats the only reason.

**Comment by leopoldhub** [comment]
Thanks

**Comment by TamtamHero** [comment]
That's fine by me :+1:

**Comment by deifactor** [comment]
For what it's worth, `pip install`-ing a Python script means that now you're dealing with installing all the dependencies into a shared package environment, which is messy. [`pipx --global`](https://pipx.pypa.io/stable/installation/#-global-argument) is probably better (I haven't used it with `--global`, but I've used it for user scripts and it's worked great).

**Comment by leopoldhub** [comment]
I think the main part of #94 is done and finished (I will use this version for the time being to test it in the long run).

I am confident that this will break existing packaging solutions, and would like to know maintainers' opinions on this in order to simplify and harmonize the required changes.

If you are a package maintainer, please reach out to me here.

Have a nice day!

> @TamtamHero 
> @Svenum 
> @icedream
> @tulilirockz

**Comment by tulilirockz** [comment]
Hello everyone! The standard pip installation most likely will just be better than the current solution as itll be a unified way of getting this installed. Most of the fedora repos is just.. python packages, so there is some amazing support for it. Just like with any other distro, really

**Comment by icedream** [comment]
I agree with @tulilirockz.

The AUR package pretty much just uses the install.sh script which I see in the PR would be updated to use pip as well. I don't expect breakage aside from validating that it still installs the resulting executable in the right place. I'd also look into how other AUR python apps are packaged, e.g. the [Arch Python package guidelines](https://wiki.archlinux.org/title/Python_package_guidelines).

**Comment by Svenum** [comment]
I will work on the Nix Package 👍

**Comment by Svenum** [comment]
@leopoldhub I have got my first successfull build, but if I want to execute the bin I got this error:

```bash
Traceback (most recent call last):
  File "/nix/store/zgr1bxvzwmdp8nbqn0hnbs9l6akm7jnh-python3.11-fw-fanctrl-20-04-2024/bin/.fw-fanctrl-wrapped", line 6, in <module>
    from fw_fanctrl.__main__ import main
  File "/nix/store/zgr1bxvzwmdp8nbqn0hnbs9l6akm7jnh-python3.11-fw-fanctrl-20-04-2024/lib/python3.11/site-packages/fw_fanctrl/__main__.py", line 4, in <module>
    from fw_fanctrl.FanController import FanController
  File "/nix/store/zgr1bxvzwmdp8nbqn0hnbs9l6akm7jnh-python3.11-fw-fanctrl-20-04-2024/lib/python3.11/site-packages/fw_fanctrl/FanController.py", line 11, in <module>
    from fw_fanctrl.dto.command_result.PrintStrategyListCommandResult import PrintStrategyListCommandResult
  File "/nix/store/zgr1bxvzwmdp8nbqn0hnbs9l6akm7jnh-python3.11-fw-fanctrl-20-04-2024/lib/python3.11/site-packages/fw_fanctrl/dto/command_result/PrintStrategyListCommandResult.py", line 13
    return f"Strategy list: {os.linesep}- {f"{os.linesep}- ".join(self.strategies)}"
                                             ^
SyntaxError: f-string: expecting '}'
```
Can you tell me where this comes from?

**Comment by leopoldhub** [comment]
Hi @Svenum , 

I suspect the `black` formatter to have replaced single quotes into double quoted in a place it  should not have.

You can temporarily fix it by replacing the problematic line:

```python
return f"Strategy list: {os.linesep}- {f'{os.linesep}- '.join(self.strategies)}"
```

I will fix this in the main and #94 ASAP

**Comment by Svenum** [comment]
This works. Nix Package is finished. 👍

**Comment by leopoldhub** [comment]
Great, waiting for final feedback on #94, thorough testing and icedream confirmation before merging.

Thanks for your help!

**Comment by leopoldhub** [comment]
I have tested it thoroughly over the last two days and there seem to be no functional problems, so I will merge it now.

As for the file structure and code formatting discussions, I will be happy to find a solution that pleases everyone in a separate issue ^^.

Thanks for everyone's work and help on this, have a great day!
