### ISSUE TITLE
[FEATURE] Package for use in atomic distros

### ISSUE THREAD

**Issue by ngraham20** [TamtamHero/fw-fanctrl#92]
**Is your feature request related to a problem? Please describe.**
I am running on Bazzite, a UniversalBlue distro (based on Fedora Silverblue), and since it's a read-only root filesystem, the python files do not have the right permissions to create the services.

**Describe the solution you'd like**
I don't know if a flatpak is even possible, though I suspect it's not. A good alternative would be to package as an RPM file, as this can be layered in as part of the OS.

**Additional context**

**Would you like to be involved in the development?**
I am happy to be involved in the development. I have *absolutely* no background in creating RPM packages, but I am willing to learn

**Comment by Svenum** [comment]
Maybe our Nix-Package is a solution for you. If you are able to install nix package manager on your distro you can install the nix package on userlevel, as far as I know.
I never used nix on non nixos-systems, and I never used Bazzite, so this is only a blind guess.

**Comment by ngraham20** [comment]
> Maybe our Nix-Package is a solution for you. If you are able to install nix package manager on your distro you can install the nix package on userlevel, as far as I know.
> I never used nix on non nixos-systems, and I never used Bazzite, so this is only a blind guess.
> 

Wouldn't it still need to copy the service files into the proper locations? I don't know how box packages deal with services. I know that they contain their own dependencies separately from the system, which I like, but the service files?

**Comment by ngraham20** [comment]
Here's an idea I'd like to play around with. Is the installation as simple as

- download ectool binary and put it in PATH
- copy the service files and enable/start them
- put the fw-fanctrl python script in PATHA

?

**Comment by ngraham20** [comment]
> https://github.com/tulilirockz/fw-fanctrl-rpm Implemented this thing!

you rock!

**Comment by butu** [comment]
How would i install this on e.g. Bluefin or any of the Ublue images?

**Comment by tulilirockz** [comment]
> How would i install this on e.g. Bluefin or any of the Ublue images?

If you'd like to layer it on top of those images, you can do this: 
```
dnf5 copr enable tulilirockz/fw-fanctrl
rpm-ostree install fw-fanctrl
```

If you are makinga custom image you can just use dnf5 to install it instead, like this:
```
dnf5 copr enable tulilirockz/fw-fanctrl
dnf5 install fw-fanctrl
```

**Comment by butu** [comment]
Great, that worked! Package is layered. Thank you!

But I can't use fw-fanctrl. Am I doing something wrong?

```
❯ fw-fanctrl
bash: fw-fanctrl: command not found
```
```
❯ rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:stable
                   Digest: sha256:c0e0a330b55a6674bdd8bf86cb6097fc1247d08ce177869bc6f00a4a36135344
                  Version: 41.20241222 (2024-12-22T06:10:08Z)
          LayeredPackages: fw-fanctrl
```

**Comment by tulilirockz** [comment]
> Great, that worked! Package is layered. Thank you!
> 
> But I can't use fw-fanctrl. Am I doing something wrong?
> 
> ```
> ❯ fw-fanctrl
> bash: fw-fanctrl: command not found
> ```
> 
> ```
> ❯ rpm-ostree status
> State: idle
> AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
> Deployments:
> ● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:stable
>                    Digest: sha256:c0e0a330b55a6674bdd8bf86cb6097fc1247d08ce177869bc6f00a4a36135344
>                   Version: 41.20241222 (2024-12-22T06:10:08Z)
>           LayeredPackages: fw-fanctrl
> ```

Oh ahahaha im sorry, I fixed this on the latest commit to the copr but I forgot to rebuild it. It should be fixed in a few minutes. You can also run the program by running `fanctrl.py` on your terminal for now

**Comment by tulilirockz** [comment]
You can check out the build on copr https://copr.fedorainfracloud.org/coprs/tulilirockz/fw-fanctrl/package/fw-fanctrl/

**Comment by tulilirockz** [comment]
Alright! You should be able to just `rpm-ostree update` your system, it should update alongside your other packages

**Comment by butu** [comment]
Aaah, I see! :D 

So a simple `rpm-ostree update` did not work, it wouldn't update. But after clearing the metadata cache with `rpm-ostree cleanup -m` it updated!

Now fw-fanctrl is available, but there seem to be more problems:

```
fw-fanctrl print
[Error] > An error occurred: [Errno 2] No such file or directory
```

```
fw-fanctrl run
Exception in thread Thread-1 (startServerSocket):
Cannot open lockfile /run/lock/cros_ec_lockCould not acquire GEC lock.
Traceback (most recent call last):
  File "/usr/lib64/python3.13/threading.py", line 1041, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "/usr/lib64/python3.13/threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/fw-fanctrl", line 349, in startServerSocket
    os.makedirs(SOCKETS_FOLDER_PATH)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 227, in makedirs
PermissionError: [Errno 13] Permission denied: '/run/fw-fanctrl'
Cannot open lockfile /run/lock/cros_ec_lockCould not acquire GEC lock.
Cannot open lockfile /run/lock/cros_ec_lockCould not acquire GEC lock.
Cannot open lockfile /run/lock/cros_ec_lockCould not acquire GEC lock.
speed: 15%, temp: 50°C, movingAverageTemp: 50.0°C, effectureTemp: 50.0°C
Cannot open lockfile /run/lock/cros_ec_lockCould not acquire GEC lock.
Cannot open lockfile /run/lock/cros_ec_lockCould not acquire GEC lock.
speed: 15%, temp: 50°C, movingAverageTemp: 50.0°C, effectureTemp: 50.0°C
Cannot open lockfile /run/lock/cros_ec_lockCould not acquire GEC lock.
Cannot open lockfile /run/lock/cros_ec_lockCould not acquire GEC lock.

```

I am sorry that I only contribute with bad news, at least it's a great learning experience for me! :D

Another idea: Considering bluefin supports Framework and the fw-fanctrl repository is very popular, could this be something for ujust in Bluefin? Like `ujust fw-fanctrl`. Or what that be completely wrong there? 

Thank you!

**Comment by leopoldhub** [comment]
Hi @tulilirockz,

Thanks for your work on the rpm package!

If you don't mind, could you please add the installation instructions to your readme so that I can link your repo as a third party rpm package?

**Comment by tulilirockz** [comment]
@leopoldhub should be there now!

**Comment by tulilirockz** [comment]
> ```
> fw-fanctrl print
> [Error] > An error occurred: [Errno 2] No such file or directory
> ```

> ```
> fw-fanctrl run
> Exception in thread Thread-1 (startServerSocket):
> Cannot open lockfile /run/lock/cros_ec_lockCould not acquire GEC lock.
> Traceback (most recent call last):
>   File "/usr/lib64/python3.13/threading.py", line 1041, in _bootstrap_inner
>     self.run()
>     ~~~~~~~~^^
>   File "/usr/lib64/python3.13/threading.py", line 992, in run
>     self._target(*self._args, **self._kwargs)
>     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/bin/fw-fanctrl", line 349, in startServerSocket
>     os.makedirs(SOCKETS_FOLDER_PATH)
>     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
>   File "<frozen os>", line 227, in makedirs
> PermissionError: [Errno 13] Permission denied: '/run/fw-fanctrl'
> Cannot open lockfile /run/lock/cros_ec_lockCould not acquire GEC lock.
> Cannot open lockfile /run/lock/cros_ec_lockCould not acquire GEC lock.
> Cannot open lockfile /run/lock/cros_ec_lockCould not acquire GEC lock.
> speed: 15%, temp: 50°C, movingAverageTemp: 50.0°C, effectureTemp: 50.0°C
> Cannot open lockfile /run/lock/cros_ec_lockCould not acquire GEC lock.
> Cannot open lockfile /run/lock/cros_ec_lockCould not acquire GEC lock.
> speed: 15%, temp: 50°C, movingAverageTemp: 50.0°C, effectureTemp: 50.0°C
> Cannot open lockfile /run/lock/cros_ec_lockCould not acquire GEC lock.
> Cannot open lockfile /run/lock/cros_ec_lockCould not acquire GEC lock.
> ```

Oh, the package might need some work too then, probably a few `systemd-tmpfiles` entries, and it should be good. I dont know exactly what is going on with your error since I dont have framework hardware to test this on.

Mind reporting this on my repo? This is most likely an issue with my package.

**Comment by tulilirockz** [comment]
The issue tracker should be here: https://github.com/tulilirockz/fw-fanctrl-rpm/issues

**Comment by leopoldhub** [comment]
Hi everyone, this issue is inactive for quite some time now.
Is the problem fixed with @tulilirockz solution ?

**Comment by ngraham20** [comment]
Yes, the COPR works great, and in Bazzite specifically, it's actually baked into the base image now
